version: '3.8'

services:
  technoback:
    build: .
    container_name: technoback
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - it_services_net
    depends_on:
      - technodb

  technodb:
    image: postgres:15
    container_name: technodb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: technopark
      POSTGRES_USER: neo
      POSTGRES_PASSWORD: MrAnderson
    networks:
      - it_services_net

volumes:
  postgres_data:

networks:
  it_services_net:
    driver: bridge
