name: Deploy to test Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions
          ssh-keyscan -H 91.243.71.68 >> ~/.ssh/known_hosts
          echo "Host 91.243.71.68\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/github-actions root@91.243.71.68 << 'EOF'
            cd /path/to/your/project
            git pull origin main
            docker compose up -d --build
          EOF
