name: Deploy to Server

on:
  push:
    branches:
      - main  # Меняй, если деплоишь другую ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Keys
        run: ssh -i ~/.ssh/id_ed25519 -vvv root@${{ secrets.SERVER_IP }} exit


      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/techno-back/techno-back
            git pull origin main
            docker compose up -d --build
          EOF
